var FLUID_DATA = [
  {
    "id": 1,
    "category": "空气类",
    "usage": "低压空气",
    "code": "ALP",
    "pfdNo": "",
    "opTemp": "30",
    "opPressure": "500",
    "density": 0.0059,
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "-",
    "chlorideConc": "-",
    "flammable": "否",
    "corrosive": "否",
    "remark": "用于工艺搅拌槽的反应供气、吹扫作业，以及过滤设备等各类装置的用气需求。",
    "name": "低压空气",
    "location": "全厂",
    "_idx": 0,
    "_merge": true,
    "_mergeSpan": 4,
    "_mergeFirst": true
  },
  {
    "id": 2,
    "category": "",
    "usage": "高压空气",
    "code": "AHP",
    "pfdNo": "",
    "opTemp": "30-100",
    "opPressure": "10500",
    "density": 0.13,
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "-",
    "chlorideConc": "-",
    "flammable": "否",
    "corrosive": "否",
    "remark": "用于工艺管道吹扫作业",
    "name": "高压空气",
    "location": "HPAL 硫酸管道吹扫",
    "_idx": 1,
    "_merge": true,
    "_mergeSpan": 4,
    "_mergeFirst": false
  },
  {
    "id": 3,
    "category": "",
    "usage": "仪表空气",
    "code": "AIN",
    "pfdNo": "",
    "opTemp": "30",
    "opPressure": "800",
    "density": 0.089,
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "-",
    "chlorideConc": "-",
    "flammable": "否",
    "corrosive": "否",
    "remark": "无油",
    "name": "仪表用气",
    "location": "全厂",
    "_idx": 2,
    "_merge": true,
    "_mergeSpan": 4,
    "_mergeFirst": false
  },
  {
    "id": 4,
    "category": "",
    "usage": "杂用空气",
    "code": "APL",
    "pfdNo": "",
    "opTemp": "40",
    "opPressure": "800",
    "density": 0.01,
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "-",
    "chlorideConc": "-",
    "flammable": "否",
    "corrosive": "否",
    "remark": "必要时，供过滤器及其他设备使用。",
    "name": "杂用风",
    "location": "全厂",
    "_idx": 3,
    "_merge": true,
    "_mergeSpan": 4,
    "_mergeFirst": false
  },
  {
    "id": 8,
    "category": "工艺溶液类",
    "usage": "高酸性溶液",
    "code": "SAH",
    "pfdNo": "",
    "opTemp": "25~100",
    "opPressure": "200~500",
    "density": "1.0-1.2",
    "solidContent": "-",
    "particleSize": "10",
    "phRange": "<2",
    "chlorideConc": "<1",
    "flammable": "否",
    "corrosive": "是",
    "remark": "含有游离酸的酸性水溶液，为浓密机溢流液。该物料固相含量通常极低，部分工况下也可为稀矿浆。",
    "name": "高酸溶液",
    "location": "CCD",
    "_idx": 4,
    "_merge": true,
    "_mergeSpan": 3,
    "_mergeFirst": true
  },
  {
    "id": 10,
    "category": "",
    "usage": "低酸性溶液",
    "code": "SAL",
    "pfdNo": "",
    "opTemp": "25~100",
    "opPressure": "200~500",
    "density": "1.0-1.2",
    "solidContent": "<1",
    "particleSize": "10",
    "phRange": "2~7",
    "chlorideConc": "<1",
    "flammable": "否",
    "corrosive": "是",
    "remark": "含潜在游离酸的酸性水溶液，来自浓密机溢流。固体含量通常极低，部分工况下该流体可为稀矿浆。",
    "name": "低酸溶液",
    "location": "除铁铝",
    "_idx": 5,
    "_merge": true,
    "_mergeSpan": 3,
    "_mergeFirst": false
  },
  {
    "id": 11,
    "category": "",
    "usage": "中性溶液",
    "code": "SNN ",
    "pfdNo": "",
    "opTemp": "25~95",
    "opPressure": "200~500",
    "density": "1.0~1.2",
    "solidContent": "<1",
    "particleSize": "10",
    "phRange": "6~8",
    "chlorideConc": "<1",
    "flammable": "否",
    "corrosive": "否",
    "remark": "中性溶液，浓密机溢流液。固体含量通常极低，部分工况下该物料流可为稀矿浆。",
    "name": "中性溶液",
    "location": "沉镍钴、尾渣压滤、产品压滤、镍钴CCD洗涤",
    "_idx": 6,
    "_merge": true,
    "_mergeSpan": 3,
    "_mergeFirst": false
  },
  {
    "id": "",
    "category": "工艺矿浆类",
    "usage": "原矿浆",
    "code": "POS",
    "pfdNo": "",
    "opTemp": "根据物料平衡",
    "opPressure": "根据物料平衡",
    "density": "1.1~1.45",
    "solidContent": "14.5-45",
    "particleSize": "-",
    "phRange": "~7",
    "chlorideConc": "根据物料平衡",
    "flammable": "否",
    "corrosive": "否",
    "remark": "",
    "name": "原矿浆",
    "location": "矿浆贮存、HPAL",
    "_idx": 7,
    "_merge": true,
    "_mergeSpan": 5,
    "_mergeFirst": true
  },
  {
    "id": 14,
    "category": "",
    "usage": "高温高压矿浆",
    "code": "SLP",
    "pfdNo": "",
    "opTemp": "165~255",
    "opPressure": "780~6000",
    "density": "根据物料平衡",
    "solidContent": "根据物料平衡",
    "particleSize": "待确认",
    "phRange": "<2",
    "chlorideConc": "根据物料平衡",
    "flammable": "否",
    "corrosive": "是",
    "remark": "",
    "name": "HPAL高压矿浆",
    "location": "HPAL",
    "_idx": 8,
    "_merge": true,
    "_mergeSpan": 5,
    "_mergeFirst": false
  },
  {
    "id": 15,
    "category": "",
    "usage": "酸性矿浆",
    "code": "SLA",
    "pfdNo": "",
    "opTemp": "根据物料平衡",
    "opPressure": "根据物料平衡",
    "density": "根据物料平衡",
    "solidContent": "根据物料平衡",
    "particleSize": "10",
    "phRange": "<6",
    "chlorideConc": "根据物料平衡",
    "flammable": "否",
    "corrosive": "是",
    "remark": "溶液中含游离酸的矿浆，例如洗涤液 / 洗涤矿浆。",
    "name": "酸性矿浆",
    "location": "HPAL,矿浆中和、除铁铝",
    "_idx": 9,
    "_merge": true,
    "_mergeSpan": 5,
    "_mergeFirst": false
  },
  {
    "id": "",
    "category": "",
    "usage": "中性或碱性矿浆",
    "code": "SLN",
    "pfdNo": "",
    "opTemp": "25~95",
    "opPressure": "400~600",
    "density": "1.1~1.3",
    "solidContent": "根据物料平衡",
    "particleSize": "10~500",
    "phRange": "6~8",
    "chlorideConc": "根据物料平衡",
    "flammable": "否",
    "corrosive": "是",
    "remark": "MHP 中性矿浆",
    "name": "中性矿浆",
    "location": "沉镍钴、产品压滤、镍钴CCD洗涤",
    "_idx": 10,
    "_merge": true,
    "_mergeSpan": 5,
    "_mergeFirst": false
  },
  {
    "id": 16,
    "category": "",
    "usage": "尾渣矿浆",
    "code": "PTA",
    "pfdNo": "",
    "opTemp": "根据物料平衡",
    "opPressure": "根据物料平衡",
    "density": "根据物料平衡",
    "solidContent": "根据物料平衡",
    "particleSize": "10",
    "phRange": ">6",
    "chlorideConc": "根据物料平衡",
    "flammable": "否",
    "corrosive": "否",
    "remark": "1.矿浆可能含有未完全反应的石灰石。\n2.存在非正常运行工况，此时矿浆呈酸性。",
    "name": "尾渣矿浆",
    "location": "尾渣中和、尾渣压滤",
    "_idx": 11,
    "_merge": true,
    "_mergeSpan": 5,
    "_mergeFirst": false
  },
  {
    "id": 17,
    "category": "工艺排气类",
    "usage": "工艺排气",
    "code": "VPR",
    "pfdNo": "",
    "opTemp": "25~100",
    "opPressure": "<20",
    "density": "根据物料平衡",
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "-",
    "chlorideConc": "-",
    "flammable": "否",
    "corrosive": "变量",
    "remark": "排放气体可能含有水蒸气、二氧化碳、酸性物质、蒸汽和 / 或空气。",
    "name": "搅拌槽排气",
    "location": "全厂",
    "_idx": 12,
    "_merge": true,
    "_mergeSpan": 2,
    "_mergeFirst": true
  },
  {
    "id": 18,
    "category": "",
    "usage": "工艺加压排气",
    "code": "VPO",
    "pfdNo": "",
    "opTemp": "90~255",
    "opPressure": "10~6000",
    "density": "根据物料平衡",
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "<6",
    "chlorideConc": "-",
    "flammable": "否",
    "corrosive": "是",
    "remark": "排放气可能含有水蒸气、酸性物质、空气等组分。",
    "name": "排气",
    "location": "HPAL",
    "_idx": 13,
    "_merge": true,
    "_mergeSpan": 2,
    "_mergeFirst": false
  },
  {
    "id": 21,
    "category": "工艺固体类",
    "usage": "尾渣压滤渣",
    "code": "SST",
    "pfdNo": "",
    "opTemp": "25~70",
    "opPressure": "-",
    "density": "根据物料平衡",
    "solidContent": "70",
    "particleSize": "-",
    "phRange": "-",
    "chlorideConc": "根据物料平衡",
    "flammable": "否",
    "corrosive": "否",
    "remark": "尾渣",
    "name": "尾渣",
    "location": "尾渣压滤",
    "_idx": 14,
    "_merge": true,
    "_mergeSpan": 2,
    "_mergeFirst": true
  },
  {
    "id": 23,
    "category": "",
    "usage": "氢氧化镍钴（MHP）物料",
    "code": "SSP",
    "pfdNo": "",
    "opTemp": "45~85",
    "opPressure": "-",
    "density": "根据物料平衡",
    "solidContent": "50",
    "particleSize": "-",
    "phRange": "-",
    "chlorideConc": "-",
    "flammable": "否",
    "corrosive": "否",
    "remark": "氢氧化镍、氢氧化钴产品",
    "name": "MHP",
    "location": "产品压滤",
    "_idx": 15,
    "_merge": true,
    "_mergeSpan": 2,
    "_mergeFirst": false
  },
  {
    "id": 25,
    "category": "试剂类",
    "usage": "浓硫酸 H2SO4",
    "code": "LSA",
    "pfdNo": "",
    "opTemp": "25~40",
    "opPressure": "200~6000",
    "density": "1.84",
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "<1",
    "chlorideConc": "<1",
    "flammable": "否",
    "corrosive": "是",
    "remark": "浓度约98%",
    "name": "浓硫酸",
    "location": "HPAL",
    "_idx": 16,
    "_merge": true,
    "_mergeSpan": 5,
    "_mergeFirst": true
  },
  {
    "id": 27,
    "category": "",
    "usage": "氢氧化钠 NaOH",
    "code": "LSH",
    "pfdNo": "",
    "opTemp": "25~40",
    "opPressure": "200~500",
    "density": "1.2~1.5",
    "solidContent": "-",
    "particleSize": "-",
    "phRange": ">14",
    "chlorideConc": "<1",
    "flammable": "否",
    "corrosive": "是",
    "remark": "浓度约 20%～50%",
    "name": "液碱",
    "location": "氢氧化钠贮槽、沉镍钴",
    "_idx": 17,
    "_merge": true,
    "_mergeSpan": 5,
    "_mergeFirst": false
  },
  {
    "id": "",
    "category": "",
    "usage": "石灰乳",
    "code": "LMS",
    "pfdNo": "",
    "opTemp": "根据物料平衡",
    "opPressure": "根据物料平衡",
    "density": "1.16",
    "solidContent": "25",
    "particleSize": "-",
    "phRange": "12 (约)",
    "chlorideConc": "根据物料平衡",
    "flammable": "否",
    "corrosive": "是",
    "remark": "",
    "name": "石灰乳",
    "location": "石灰乳制备、沉镍钴、尾渣中和",
    "_idx": 18,
    "_merge": true,
    "_mergeSpan": 5,
    "_mergeFirst": false
  },
  {
    "id": "",
    "category": "",
    "usage": "石灰石矿浆",
    "code": "LLS",
    "pfdNo": "",
    "opTemp": "根据物料平衡",
    "opPressure": "根据物料平衡",
    "density": "1.28~1.39",
    "solidContent": "30 - 40",
    "particleSize": "10",
    "phRange": "9 (约)",
    "chlorideConc": "根据物料平衡",
    "flammable": "否",
    "corrosive": "是",
    "remark": "使用工艺水",
    "name": "石灰石浆",
    "location": "矿浆中和、沉镍钴、除铁铝",
    "_idx": 19,
    "_merge": true,
    "_mergeSpan": 5,
    "_mergeFirst": false
  },
  {
    "id": "",
    "category": "",
    "usage": "絮凝剂",
    "code": "LFL",
    "pfdNo": "",
    "opTemp": "根据物料平衡",
    "opPressure": "根据物料平衡",
    "density": "1.0",
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "6~9",
    "chlorideConc": "变量",
    "flammable": "否",
    "corrosive": "否",
    "remark": "以工艺水配制的絮凝剂溶液",
    "name": "絮凝剂",
    "location": "全厂",
    "_idx": 20,
    "_merge": true,
    "_mergeSpan": 5,
    "_mergeFirst": false
  },
  {
    "id": 29,
    "category": "蒸汽类",
    "usage": "高压蒸汽",
    "code": "GSH",
    "pfdNo": "",
    "opTemp": "根据物料平衡",
    "opPressure": "根据物料平衡",
    "density": "根据物料平衡",
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "-",
    "chlorideConc": "<1",
    "flammable": "否",
    "corrosive": "否",
    "remark": "用于高压酸浸",
    "name": "高压蒸汽",
    "location": "HPAL",
    "_idx": 21,
    "_merge": true,
    "_mergeSpan": 2,
    "_mergeFirst": true
  },
  {
    "id": 31,
    "category": "",
    "usage": "工艺闪蒸蒸汽",
    "code": "STF",
    "pfdNo": "",
    "opTemp": "根据物料平衡",
    "opPressure": "根据物料平衡",
    "density": "根据物料平衡",
    "solidContent": "<3.0",
    "particleSize": "待确认",
    "phRange": "-",
    "chlorideConc": "-",
    "flammable": "否",
    "corrosive": "是",
    "remark": "闪蒸 / 蒸发蒸汽可源自酸性、中性或碱性工艺系统（含夹带物料）",
    "name": "闪蒸蒸汽",
    "location": "HPAL",
    "_idx": 22,
    "_merge": true,
    "_mergeSpan": 2,
    "_mergeFirst": false
  },
  {
    "id": 33,
    "category": "水类",
    "usage": "工艺水",
    "code": "WPR",
    "pfdNo": "",
    "opTemp": "根据物料平衡",
    "opPressure": "200~1600",
    "density": 1,
    "solidContent": "<0.1",
    "particleSize": "-",
    "phRange": "6~8",
    "chlorideConc": "待确认",
    "flammable": "否",
    "corrosive": "否",
    "remark": "用作除盐水、消防水、冷却水水源",
    "name": "工艺水",
    "location": "全厂",
    "_idx": 23,
    "_merge": true,
    "_mergeSpan": 6,
    "_mergeFirst": true
  },
  {
    "id": 34,
    "category": "",
    "usage": "脱盐水",
    "code": "WDI",
    "pfdNo": "",
    "opTemp": "根据物料平衡",
    "opPressure": "200~500",
    "density": 1,
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "6~8",
    "chlorideConc": "<1",
    "flammable": "否",
    "corrosive": "否",
    "remark": "高压酸浸设备用水",
    "name": "脱盐水",
    "location": "HPAL",
    "_idx": 24,
    "_merge": true,
    "_mergeSpan": 6,
    "_mergeFirst": false
  },
  {
    "id": 35,
    "category": "",
    "usage": "冷却水给水",
    "code": "WCS",
    "pfdNo": "",
    "opTemp": "33",
    "opPressure": "200~500",
    "density": 1,
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "6~8",
    "chlorideConc": "跟工艺水要求一致",
    "flammable": "否",
    "corrosive": "否",
    "remark": "",
    "name": "循环水给水",
    "location": "HPAL",
    "_idx": 25,
    "_merge": true,
    "_mergeSpan": 6,
    "_mergeFirst": false
  },
  {
    "id": 36,
    "category": "",
    "usage": "冷却水回水",
    "code": "WCR",
    "pfdNo": "",
    "opTemp": "40",
    "opPressure": "200~500",
    "density": 1,
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "6~8",
    "chlorideConc": "跟工艺水要求一致",
    "flammable": "否",
    "corrosive": "否",
    "remark": "",
    "name": "循环水回水",
    "location": "HPAL",
    "_idx": 26,
    "_merge": true,
    "_mergeSpan": 6,
    "_mergeFirst": false
  },
  {
    "id": 37,
    "category": "",
    "usage": "密封水",
    "code": "WAS",
    "pfdNo": "",
    "opTemp": "25~40",
    "opPressure": "根据物料平衡",
    "density": 1,
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "6~9",
    "chlorideConc": "<1",
    "flammable": "否",
    "corrosive": "否",
    "remark": "用于高压釜搅拌系统",
    "name": "密封水",
    "location": "HPAL",
    "_idx": 27,
    "_merge": true,
    "_mergeSpan": 6,
    "_mergeFirst": false
  },
  {
    "id": 38,
    "category": "",
    "usage": "消防水",
    "code": "WFI",
    "pfdNo": "",
    "opTemp": "25~40",
    "opPressure": "待确认",
    "density": 1,
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "6~9",
    "chlorideConc": "跟工艺水要求一致",
    "flammable": "否",
    "corrosive": "否",
    "remark": "",
    "name": "消防水",
    "location": "全厂",
    "_idx": 28,
    "_merge": true,
    "_mergeSpan": 6,
    "_mergeFirst": false
  },
  {
    "id": 40,
    "category": "排水类",
    "usage": "洗涤废水或雨水排放 — 酸性",
    "code": "DEA",
    "pfdNo": "",
    "opTemp": "30",
    "opPressure": "<500",
    "density": 1,
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "<6",
    "chlorideConc": "变量",
    "flammable": "否",
    "corrosive": "是",
    "remark": "",
    "name": "酸性污水",
    "location": "全厂",
    "_idx": 29,
    "_merge": true,
    "_mergeSpan": 3,
    "_mergeFirst": true
  },
  {
    "id": 41,
    "category": "",
    "usage": "洗涤废水或雨水排放 — 碱性",
    "code": "DEL",
    "pfdNo": "",
    "opTemp": "30",
    "opPressure": "<500",
    "density": 1,
    "solidContent": "-",
    "particleSize": "-",
    "phRange": ">8",
    "chlorideConc": "<500",
    "flammable": "否",
    "corrosive": "是",
    "remark": "",
    "name": "碱性污水",
    "location": "全厂",
    "_idx": 30,
    "_merge": true,
    "_mergeSpan": 3,
    "_mergeFirst": false
  },
  {
    "id": 42,
    "category": "",
    "usage": "洗涤废水或雨水排放 — 中性",
    "code": "DEN",
    "pfdNo": "",
    "opTemp": "30",
    "opPressure": "<500",
    "density": 1,
    "solidContent": "-",
    "particleSize": "-",
    "phRange": "6-8",
    "chlorideConc": "<500",
    "flammable": "否",
    "corrosive": "否",
    "remark": "",
    "name": "中性污水",
    "location": "全厂",
    "_idx": 31,
    "_merge": true,
    "_mergeSpan": 3,
    "_mergeFirst": false
  }
];